website/moodways/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('website.urls', namespace='website')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^blog/list/$',
        FrontBlogListView.as_view(), name="frontBlogList"),
    url(r'^blog/(?P<pk>\d+)/$',
        FrontBlogDetailView.as_view(), name='frontBlogDetail'),
    url(r'^page/(?P<slug>[\w-]+)/$',
        FrontPageDetailView.as_view(), name='frontPageDetail'),

    url(r'^package/list/$',
        FrontPackageListView.as_view(), name="frontPackageList"),
    url(r'^package/(?P<slug>[\w-]+)/$',
        FrontPackageDetailView.as_view(), name='frontPackageDetail'),


    url(r'^package/(?P<slug>[\w-]+)/book$',
        FrontPackageBookingView.as_view(), name="frontPackageBooking"),

    url(r'git-pull/$', GitPullView.as_view(), name='git_pull'),


    url(r'^moodwaysAdmin/$', Dashboard.as_view(), name="dashboard_main"),
    url(r'^moodwaysAdmin/dashboard/$', Dashboard.as_view(), name="dashboard"),


    url(r'^register/$', RegistrationView.as_view(), name="register"),
    url(r'^moodwaysAdmin/login/$', LoginView.as_view(), name="login"),
    url(r'^moodwaysAdmin/logout/$', LogoutView.as_view(), name="logout"),

    url(r'^moodwaysAdmin/gallery/create/$',
        GalleryCreateView.as_view(), name="galleryCreate"),
    url(r'^moodwaysAdmin/gallery/list/$',
        GalleryListView.as_view(), name="galleryList"),
    url(r'^moodwaysAdmin/gallery/(?P<pk>\d+)/update/$',
        GalleryUpdateView.as_view(), name="galleryUpdate"),
    url(r'^moodwaysAdmin/gallery/(?P<pk>\d+)/$',
        GalleryDetailView.as_view(), name="galleryDetail"),
    url(r'^moodwaysAdmin/photo/(?P<pk>\d+)/update/$',
        PhotoUpdateView.as_view(), name="photoUpdate"),

    url(r'^moodwaysAdmin/gallery/(?P<pk>\d+)/delete/$',
        GalleryDeleteView.as_view(), name="galleryDelete"),
    url(r'^moodwaysAdmin/photo/(?P<pk>\d+)/delete/$',
        PhotoDeleteView.as_view(), name="photoDelete"),


    url(r'^moodwaysAdmin/place/create/$',
        PlaceCreateView.as_view(), name="placeCreate"),
    url(r'^moodwaysAdmin/place/list/$',
        PlaceListView.as_view(), name="placeList"),
    url(r'^moodwaysAdmin/place/(?P<pk>\d+)/update/$',
        PlaceUpdateView.as_view(), name='placeUpdate'),
    url(r'^moodwaysAdmin/place/(?P<pk>\d+)/delete/$',
        PlaceDeleteView.as_view(), name="placeDelete"),


    url(r'^moodwaysAdmin/days/create/$',
        DaysCreateView.as_view(), name="daysCreate"),
    url(r'^moodwaysAdmin/days/list/$',
        DaysListView.as_view(), name="daysList"),
    url(r'^moodwaysAdmin/days/(?P<pk>\d+)/update/$',
        DaysUpdateView.as_view(), name="daysUpdate"),
    url(r'^moodwaysAdmin/days/(?P<pk>\d+)/delete/$',
        DaysDeleteView.as_view(), name="daysDelete"),


    url(r'^moodwaysAdmin/season/create/$',
        SeasonCreateView.as_view(), name="seasonCreate"),
    url(r'^moodwaysAdmin/season/list/$',
        SeasonListView.as_view(), name="seasonList"),
    url(r'^moodwaysAdmin/season/(?P<pk>\d+)/update/$',
        SeasonUpdateView.as_view(), name='seasonUpdate'),
    url(r'^moodwaysAdmin/season/(?P<pk>\d+)/delete/$',
        SeasonDeleteView.as_view(), name="seasonDelete"),

    url(r'^moodwaysAdmin/page/create/$',
        PageCreateView.as_view(), name="pageCreate"),
    url(r'^moodwaysAdmin/page/list/$',
        PageListView.as_view(), name="pageList"),
    url(r'^moodwaysAdmin/page/(?P<pk>\d+)/update/$',
        PageUpdateView.as_view(), name='pageUpdate'),
    url(r'^moodwaysAdmin/page/(?P<pk>\d+)/$',
        PageDetailView.as_view(), name='pageDetail'),
    url(r'^moodwaysAdmin/page/(?P<pk>\d+)/delete/$',
        PageDeleteView.as_view(), name="pageDelete"),

    url(r'^moodwaysAdmin/blog/create/$',
        BlogCreateView.as_view(), name="blogCreate"),
    url(r'^moodwaysAdmin/blog/list/$',
        BlogListView.as_view(), name="blogList"),
    url(r'^moodwaysAdmin/blog/(?P<pk>\d+)/update/$',
        BlogUpdateView.as_view(), name='blogUpdate'),
    url(r'^moodwaysAdmin/blog/(?P<pk>\d+)/$',
        BlogDetailView.as_view(), name='blogDetail'),
    url(r'^moodwaysAdmin/blog/(?P<pk>\d+)/delete/$',
        BlogDeleteView.as_view(), name="blogDelete"),


    url(r'^moodwaysAdmin/package/create/$',
        PackageCreateView.as_view(), name="packageCreate"),
    url(r'^moodwaysAdmin/package/list/$',
        PackageListView.as_view(), name="packageList"),
    url(r'^moodwaysAdmin/package/(?P<pk>\d+)/update/$',
        PackageUpdateView.as_view(), name="packageUpdate"),
    url(r'^moodwaysAdmin/package/(?P<pk>\d+)/$',
        PackageDetailView.as_view(), name="packageDetail"),
    url(r'^moodwaysAdmin/itenary/(?P<pk>\d+)/update/$',
        ItenaryUpdateView.as_view(), name="itenaryUpdate"),

    url(r'^moodwaysAdmin/package/(?P<pk>\d+)/delete/$',
        PackageDeleteView.as_view(), name="packageDelete"),
    url(r'^moodwaysAdmin/itenary/(?P<pk>\d+)/delete/$',
        ItenaryDeleteView.as_view(), name="itenaryDelete"),


    url(r'^moodwaysAdmin/comment/list/$',
        CommentListView.as_view(), name="commentList"),
    url(r'^moodwaysAdmin/comment/(?P<pk>\d+)/$',
        CommentDetailView.as_view(), name='commentDetail'),
    url(r'^moodwaysAdmin/comment/(?P<pk>\d+)/toggle$',
        CommentApproveDisapproveView.as_view(), name='commentToggle'),
    url(r'^moodwaysAdmin/comment/(?P<pk>\d+)/delete/$',
        CommentDeleteView.as_view(), name="commentDelete"),


    url(r'^moodwaysAdmin/menu/list/$',
        MenuListView.as_view(), name='menuList'),
    url(r'^moodwaysAdmin/menu/create/$',
        MenuCreateView.as_view(), name='menuCreate'),
    url(r'^moodwaysAdmin/menu/(?P<pk>[\d]+)/$',
        MenuDetailView.as_view(), name='menuDetail'),
    url(r'^moodwaysAdmin/menu/(?P<pk>[\d]+)/update/$',
        MenuUpdateView.as_view(), name='menuUpdate'),
    url(r'^moodwaysAdmin/menu/(?P<pk>[\d]+)/delete/$',
        MenuDeleteView.as_view(), name='menuDelete'),

    url(r'^moodwaysAdmin/slider/list/$',
        SliderListView.as_view(), name='sliderList'),
    url(r'^moodwaysAdmin/slider/create/$',
        SliderCreateView.as_view(), name='sliderCreate'),
    url(r'^moodwaysAdmin/slider/(?P<pk>[\d]+)/$',
        SliderDetailView.as_view(), name='sliderDetail'),
    url(r'^moodwaysAdmin/slider/(?P<pk>[\d]+)/update/$',
        SliderUpdateView.as_view(), name='sliderUpdate'),
    url(r'^moodwaysAdmin/slider/(?P<pk>[\d]+)/delete/$',
        SliderDeleteView.as_view(), name='sliderDelete'),

    url(r'^moodwaysAdmin/trailer/list/$',
        TrailerListView.as_view(), name='trailerList'),
    url(r'^moodwaysAdmin/trailer/create/$',
        TrailerCreateView.as_view(), name='trailerCreate'),
    url(r'^moodwaysAdmin/trailer/(?P<pk>[\d]+)/$',
        TrailerDetailView.as_view(), name='trailerDetail'),
    url(r'^moodwaysAdmin/trailer/(?P<pk>[\d]+)/update/$',
        TrailerUpdateView.as_view(), name='trailerUpdate'),
    url(r'^moodwaysAdmin/trailer/(?P<pk>[\d]+)/delete/$',
        TrailerDeleteView.as_view(), name='trailerDelete'),

    url(r'^moodwaysAdmin/booking/list/$',
        BookingListView.as_view(), name="bookingList"),
    url(r'^moodwaysAdmin/booking/(?P<pk>[\d]+)/$',
        BookingDetailView.as_view(), name="bookingDetail"),

    url(r'^moodwaysAdmin/coupon/create/$',
        CouponCreateView.as_view(), name="couponCreate"),
    url(r'^moodwaysAdmin/coupon/list/$',
        CouponListView.as_view(), name="couponList"),
    url(r'^moodwaysAdmin/coupon/(?P<pk>\d+)/update/$',
        CouponUpdateView.as_view(), name='couponUpdate'),
    url(r'^moodwaysAdmin/coupon/(?P<pk>\d+)/delete/$',
        CouponDeleteView.as_view(), name='couponDelete'),



]

website/templates/layouts/admin/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>{% block head_title %}Moodways Admin Panel{% endblock %}</title>
    {% include "layouts/admin/include/head.html" %}
    {% block extra_head %}
    {% endblock %}
</head>
<body class="menubar-hoverable header-fixed full-content">
    <!-- BEGIN HEADER-->
    <header id="header" >
        <div class="headerbar">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="headerbar-left">
                <ul class="header-nav header-nav-options">
                    <li class="header-nav-brand" >
                        <div class="brand-holder">
                            <a href="">
                                <span class="text-lg text-bold text-primary">MOODWAYS ADMIN</span>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="headerbar-right">

                <ul class="header-nav header-nav-profile">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
                            <span class="profile-info">
                                {{request.user.get_full_name}}
                                <small> Administrator</small>
                            </span>
                        </a>
                        <ul class="dropdown-menu animation-dock">
                            <li><a href="#"  data-toggle="modal" data-target="#logOutModal"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
                        </ul><!--end .dropdown-menu -->
                    </li><!--end .dropdown -->
                </ul><!--end .header-nav-profile -->
            </div><!--end #header-navbar-collapse -->
        </div>
    </header>
    <!-- END HEADER-->

    <div class="modal fade" id="logOutModal" tabindex="-1" role="dialog" aria-labelledby="logOutModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="simpleModalLabel">Log Out</h4>
                </div>
                <div class="modal-body">
                    <p>Do you want to logout?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary"><a href="{% url 'website:logout' %}"  style="text-decoration:none;">Logout</a></button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <!-- END SIMPLE MODAL MARKUP -->


    <!-- BEGIN BASE-->
    <div id="base">
        {% if messages %}
        {% for message in messages %}
        <div id="toast-container" class="toast-bottom-right" aria-live="polite" role="alert">
           <div class="toast toast-{{message.tags}}">
               <div class="toast-message">{{ message }}</div>
           </div>
       </div>
       {% endfor %}
       {% endif %}
       <!-- BEGIN CONTENT-->
       <div id="content">

        {% block content %}
        {% endblock %}

    </div><!--end #content-->
    <!-- END CONTENT -->
    {% block menubar%}
    <!-- BEGIN MENUBAR-->
    <div id="menubar" class="menubar-inverse ">
        <div class="menubar-fixed-panel">
            <div>
                <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                    <i class="fa fa-bars"></i>
                </a>
            </div>
            <div class="expanded">
                <a href="">
                    <span class="text-lg text-bold text-primary ">MOODWAYS&nbsp;ADMIN</span>
                </a>
            </div>
        </div>
        <div class="menubar-scroll-panel">

            <!-- BEGIN MAIN MENU -->
            <ul id="main-menu" class="gui-controls">

                <!-- BEGIN DASHBOARD -->
                <li>
                    <a href="{% url 'website:dashboard' %}" id="dashboard">
                        <div class="gui-icon"><i class="fa fa-dashboard"></i></div>
                        <span class="title">Dashboard</span>
                    </a>
                </li><!--end /menu-li -->
                <!-- END DASHBOARD -->

                <li>
                    <a href="{% url 'website:blogList' %}" id="blog">
                        <div class="gui-icon"><i class="fa fa-newspaper-o"></i></div>
                        <span class="title">Blog</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:bookingList' %}" id="booking">
                        <div class="gui-icon"><i class="fa fa-book"></i></div>
                        <span class="title">Booking</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:commentList' %}" id="comment">
                        <div class="gui-icon"><i class="fa fa-comment"></i></div>
                        <span class="title">Comment</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:couponList' %}" id="coupon">
                        <div class="gui-icon"><i class="fa fa-gift"></i></div>
                        <span class="title">Coupon</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:daysList' %}" id="days">
                        <div class="gui-icon"><i class="fa fa-calendar"></i></div>
                        <span class="title">Days</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:galleryList' %}" id="gallery">
                        <div class="gui-icon"><i class="fa fa-photo"></i></div>
                        <span class="title">Gallery</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:menuList' %}" id="menu">
                        <div class="gui-icon"><i class="fa fa-navicon"></i></div>
                        <span class="title">Menu</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:packageList' %}" id="package">
                        <div class="gui-icon"><i class="fa fa-plane"></i></div>
                        <span class="title">Package</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:pageList' %}" id="page">
                        <div class="gui-icon"><i class="fa fa-file-powerpoint-o"></i></div>
                        <span class="title">Page</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:placeList' %}" id="place">
                        <div class="gui-icon"><i class="fa fa-cab"></i></div>
                        <span class="title">Place</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:seasonList' %}" id="season">
                        <div class="gui-icon"><i class="fa fa-cloud"></i></div>
                        <span class="title">Season</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:sliderList' %}" id="slider">
                        <div class="gui-icon"><i class="fa fa-photo"></i></div>
                        <span class="title">Slider</span>
                    </a>
                </li><!--end /menu-li -->
                <li>
                    <a href="{% url 'website:trailerList' %}" id="trailer">
                        <div class="gui-icon"><i class="fa fa-youtube-play"></i></div>
                        <span class="title">Trailer</span>
                    </a>
                </li><!--end /menu-li -->
            </ul><!--end .main-menu -->
            <!-- END MAIN MENU -->

            <div class="menubar-foot-panel">
                <small class="no-linebreak hidden-folded">
                    <span class="opacity-75">Copyright &copy; 2017</span> <strong>Prixa</strong>
                </small>
            </div>
        </div><!--end .menubar-scroll-panel-->
    </div><!--end #menubar-->
    <!-- END MENUBAR -->
    {% endblock menubar %}
    </div><!--end #base-->
<!-- END BASE -->

    {% include "layouts/admin/include/javascript.html" %}
    <script type="text/javascript">
        $(function(){
            {% if messages %}
            toastr.clear();
            {% for message in messages %}
            toastr.options.closeButton = true;
            toastr.options.progressBar = true;
            toastr.options.debug = false;
            toastr.options.positionClass = 'toast-bottom-right';
            toastr.options.showDuration = 333;
            toastr.options.hideDuration = 333;
            toastr.options.timeOut = 4000;
            toastr.options.extendedTimeOut = 4000;
            toastr.options.showEasing = 'swing';
            toastr.options.hideEasing = 'swing';
            toastr.options.showMethod = 'slideDown';
            toastr.options.hideMethod = 'slideUp';
            toastr.{{message.tags}}('{{message}}', '');
            {% endfor %}
            {% endif %}
        });

    </script>
    {% block extra_js %}
    {% endblock extra_js %}
</body>
</html>