website/moodways/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('website.urls', namespace='website')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^blog/list/$',
        FrontBlogListView.as_view(), name="frontBlogList"),
    url(r'^blog/(?P<pk>\d+)/$',
        FrontBlogDetailView.as_view(), name='frontBlogDetail'),
    url(r'^page/(?P<slug>[\w-]+)/$',
        FrontPageDetailView.as_view(), name='frontPageDetail'),

    url(r'^package/list/$',
        FrontPackageListView.as_view(), name="frontPackageList"),
    url(r'^package/(?P<slug>[\w-]+)/$',
        FrontPackageDetailView.as_view(), name='frontPackageDetail'),


    url(r'^package/(?P<slug>[\w-]+)/book$',
        FrontPackageBookingView.as_view(), name="frontPackageBooking"),

    url(r'git-pull/$', GitPullView.as_view(), name='git_pull'),


    url(r'^moodwaysAdmin/$', Dashboard.as_view(), name="dashboard_main"),
    url(r'^moodwaysAdmin/dashboard/$', Dashboard.as_view(), name="dashboard"),


    url(r'^register/$', RegistrationView.as_view(), name="register"),
    url(r'^moodwaysAdmin/login/$', LoginView.as_view(), name="login"),
    url(r'^moodwaysAdmin/logout/$', LogoutView.as_view(), name="logout"),

    url(r'^moodwaysAdmin/gallery/create/$',
        GalleryCreateView.as_view(), name="galleryCreate"),
    url(r'^moodwaysAdmin/gallery/list/$',
        GalleryListView.as_view(), name="galleryList"),
    url(r'^moodwaysAdmin/gallery/(?P<pk>\d+)/update/$',
        GalleryUpdateView.as_view(), name="galleryUpdate"),
    url(r'^moodwaysAdmin/gallery/(?P<pk>\d+)/$',
        GalleryDetailView.as_view(), name="galleryDetail"),
    url(r'^moodwaysAdmin/photo/(?P<pk>\d+)/update/$',
        PhotoUpdateView.as_view(), name="photoUpdate"),

    url(r'^moodwaysAdmin/gallery/(?P<pk>\d+)/delete/$',
        GalleryDeleteView.as_view(), name="galleryDelete"),
    url(r'^moodwaysAdmin/photo/(?P<pk>\d+)/delete/$',
        PhotoDeleteView.as_view(), name="photoDelete"),


    url(r'^moodwaysAdmin/place/create/$',
        PlaceCreateView.as_view(), name="placeCreate"),
    url(r'^moodwaysAdmin/place/list/$',
        PlaceListView.as_view(), name="placeList"),
    url(r'^moodwaysAdmin/place/(?P<pk>\d+)/update/$',
        PlaceUpdateView.as_view(), name='placeUpdate'),
    url(r'^moodwaysAdmin/place/(?P<pk>\d+)/delete/$',
        PlaceDeleteView.as_view(), name="placeDelete"),


    url(r'^moodwaysAdmin/days/create/$',
        DaysCreateView.as_view(), name="daysCreate"),
    url(r'^moodwaysAdmin/days/list/$',
        DaysListView.as_view(), name="daysList"),
    url(r'^moodwaysAdmin/days/(?P<pk>\d+)/update/$',
        DaysUpdateView.as_view(), name="daysUpdate"),
    url(r'^moodwaysAdmin/days/(?P<pk>\d+)/delete/$',
        DaysDeleteView.as_view(), name="daysDelete"),


    url(r'^moodwaysAdmin/season/create/$',
        SeasonCreateView.as_view(), name="seasonCreate"),
    url(r'^moodwaysAdmin/season/list/$',
        SeasonListView.as_view(), name="seasonList"),
    url(r'^moodwaysAdmin/season/(?P<pk>\d+)/update/$',
        SeasonUpdateView.as_view(), name='seasonUpdate'),
    url(r'^moodwaysAdmin/season/(?P<pk>\d+)/delete/$',
        SeasonDeleteView.as_view(), name="seasonDelete"),

    url(r'^moodwaysAdmin/page/create/$',
        PageCreateView.as_view(), name="pageCreate"),
    url(r'^moodwaysAdmin/page/list/$',
        PageListView.as_view(), name="pageList"),
    url(r'^moodwaysAdmin/page/(?P<pk>\d+)/update/$',
        PageUpdateView.as_view(), name='pageUpdate'),
    url(r'^moodwaysAdmin/page/(?P<pk>\d+)/$',
        PageDetailView.as_view(), name='pageDetail'),
    url(r'^moodwaysAdmin/page/(?P<pk>\d+)/delete/$',
        PageDeleteView.as_view(), name="pageDelete"),

    url(r'^moodwaysAdmin/blog/create/$',
        BlogCreateView.as_view(), name="blogCreate"),
    url(r'^moodwaysAdmin/blog/list/$',
        BlogListView.as_view(), name="blogList"),
    url(r'^moodwaysAdmin/blog/(?P<pk>\d+)/update/$',
        BlogUpdateView.as_view(), name='blogUpdate'),
    url(r'^moodwaysAdmin/blog/(?P<pk>\d+)/$',
        BlogDetailView.as_view(), name='blogDetail'),
    url(r'^moodwaysAdmin/blog/(?P<pk>\d+)/delete/$',
        BlogDeleteView.as_view(), name="blogDelete"),


    url(r'^moodwaysAdmin/package/create/$',
        PackageCreateView.as_view(), name="packageCreate"),
    url(r'^moodwaysAdmin/package/list/$',
        PackageListView.as_view(), name="packageList"),
    url(r'^moodwaysAdmin/package/(?P<pk>\d+)/update/$',
        PackageUpdateView.as_view(), name="packageUpdate"),
    url(r'^moodwaysAdmin/package/(?P<pk>\d+)/$',
        PackageDetailView.as_view(), name="packageDetail"),
    url(r'^moodwaysAdmin/itenary/(?P<pk>\d+)/update/$',
        ItenaryUpdateView.as_view(), name="itenaryUpdate"),

    url(r'^moodwaysAdmin/package/(?P<pk>\d+)/delete/$',
        PackageDeleteView.as_view(), name="packageDelete"),
    url(r'^moodwaysAdmin/itenary/(?P<pk>\d+)/delete/$',
        ItenaryDeleteView.as_view(), name="itenaryDelete"),


    url(r'^moodwaysAdmin/comment/list/$',
        CommentListView.as_view(), name="commentList"),
    url(r'^moodwaysAdmin/comment/(?P<pk>\d+)/$',
        CommentDetailView.as_view(), name='commentDetail'),
    url(r'^moodwaysAdmin/comment/(?P<pk>\d+)/toggle$',
        CommentApproveDisapproveView.as_view(), name='commentToggle'),
    url(r'^moodwaysAdmin/comment/(?P<pk>\d+)/delete/$',
        CommentDeleteView.as_view(), name="commentDelete"),


    url(r'^moodwaysAdmin/menu/list/$',
        MenuListView.as_view(), name='menuList'),
    url(r'^moodwaysAdmin/menu/create/$',
        MenuCreateView.as_view(), name='menuCreate'),
    url(r'^moodwaysAdmin/menu/(?P<pk>[\d]+)/$',
        MenuDetailView.as_view(), name='menuDetail'),
    url(r'^moodwaysAdmin/menu/(?P<pk>[\d]+)/update/$',
        MenuUpdateView.as_view(), name='menuUpdate'),
    url(r'^moodwaysAdmin/menu/(?P<pk>[\d]+)/delete/$',
        MenuDeleteView.as_view(), name='menuDelete'),

    url(r'^moodwaysAdmin/slider/list/$',
        SliderListView.as_view(), name='sliderList'),
    url(r'^moodwaysAdmin/slider/create/$',
        SliderCreateView.as_view(), name='sliderCreate'),
    url(r'^moodwaysAdmin/slider/(?P<pk>[\d]+)/$',
        SliderDetailView.as_view(), name='sliderDetail'),
    url(r'^moodwaysAdmin/slider/(?P<pk>[\d]+)/update/$',
        SliderUpdateView.as_view(), name='sliderUpdate'),
    url(r'^moodwaysAdmin/slider/(?P<pk>[\d]+)/delete/$',
        SliderDeleteView.as_view(), name='sliderDelete'),

    url(r'^moodwaysAdmin/trailer/list/$',
        TrailerListView.as_view(), name='trailerList'),
    url(r'^moodwaysAdmin/trailer/create/$',
        TrailerCreateView.as_view(), name='trailerCreate'),
    url(r'^moodwaysAdmin/trailer/(?P<pk>[\d]+)/$',
        TrailerDetailView.as_view(), name='trailerDetail'),
    url(r'^moodwaysAdmin/trailer/(?P<pk>[\d]+)/update/$',
        TrailerUpdateView.as_view(), name='trailerUpdate'),
    url(r'^moodwaysAdmin/trailer/(?P<pk>[\d]+)/delete/$',
        TrailerDeleteView.as_view(), name='trailerDelete'),

    url(r'^moodwaysAdmin/booking/list/$',
        BookingListView.as_view(), name="bookingList"),
    url(r'^moodwaysAdmin/booking/(?P<pk>[\d]+)/$',
        BookingDetailView.as_view(), name="bookingDetail"),

    url(r'^moodwaysAdmin/coupon/create/$',
        CouponCreateView.as_view(), name="couponCreate"),
    url(r'^moodwaysAdmin/coupon/list/$',
        CouponListView.as_view(), name="couponList"),
    url(r'^moodwaysAdmin/coupon/(?P<pk>\d+)/update/$',
        CouponUpdateView.as_view(), name='couponUpdate'),
    url(r'^moodwaysAdmin/coupon/(?P<pk>\d+)/delete/$',
        CouponDeleteView.as_view(), name='couponDelete'),



]

website/website/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.core.urlresolvers import reverse


# Create your models here.

class Timestampable(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Gallery(Timestampable):
    name = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse("website:galleryDetail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Gallery"
        verbose_name_plural = "Galleries"


class Photo(Timestampable):
    photo = models.ImageField()
    caption = models.CharField(max_length=255, null=True, blank=True)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)

    def __str__(self):
        return self.gallery.name + " " + str(self.pk)

    class Meta:
        verbose_name = "Photo"
        verbose_name_plural = "Photos"


class Place(Timestampable):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Place"
        verbose_name_plural = "Places"


class Days(Timestampable):
    min = models.IntegerField(default=0)
    max = models.IntegerField(default=0)

    def __str__(self):
        return str(str(self.min) + "-" + str(self.max) + " Days ")

    class Meta:
        verbose_name = "Day"
        verbose_name_plural = "Days"


class Season(Timestampable):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Season"
        verbose_name_plural = "Seasons"


class Package(Timestampable):
    title = models.CharField(max_length=1024)
    slug = models.SlugField(unique=True)
    subTitle = models.CharField(max_length=1024, null=True, blank=True)
    titlePic = models.ImageField(null=True, blank=True)
    caption = models.CharField(max_length=255, null=True, blank=True)
    body = RichTextField()
    price = models.FloatField(default=0, null=True, blank=True)
    discount = models.FloatField(default=0, null=True, blank=True)
    gallery = models.ForeignKey(Gallery, null=True, blank=True)
    place = models.ForeignKey(Place, null=True, blank=True)
    day = models.ForeignKey(Days, null=True, blank=True)
    season = models.ForeignKey(Season, null=True, blank=True)
    is_promotional = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("website:packageDetail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Package"
        verbose_name_plural = "Packages"
        ordering = ('-created_at',)
        


class Itenary(Timestampable):
    package = models.ForeignKey(Package, on_delete=models.CASCADE)
    day = models.CharField(max_length=255)
    description = RichTextField()

    def __str__(self):
        return self.day

    class Meta:
        verbose_name = "Iternary"
        verbose_name_plural = "Iternaries"
        ordering = ["day"]


class Blog(Timestampable):
    author = models.CharField(max_length=255, null=True, blank=True)
    authorPic = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=255)
    subTitle = models.CharField(max_length=255, null=True, blank=True)
    titlePic = models.ImageField(null=True, blank=True)
    caption = models.CharField(max_length=255, null=True, blank=True)
    body = RichTextField()

    def get_absolute_url(self):
        return reverse("website:frontBlogDetail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blogs"
        ordering = ('-created_at',)


class Comment(Timestampable):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"


class Page(Timestampable):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    body = RichTextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Page"
        verbose_name_plural = "Pages"


class Booking(Timestampable):
    package = models.ForeignKey(Package, on_delete=models.CASCADE)
    person = models.PositiveIntegerField(default=1)
    travelDate = models.DateField()
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    discount_code = models.CharField(max_length=15,null=True, blank=True)
    comments = models.TextField()

    def __str__(self):
        return self.name + " " + self.package.title


class Menu(Timestampable):
    title = models.CharField(max_length=255)
    url = models.CharField(max_length=50, help_text='/pages/1/')
    priority = models.IntegerField(
        help_text='Lower number comes first in menu', null=False, blank=False)
    parent = models.ForeignKey(
        'self', related_name='children', null=True, blank=True)

    class Meta:
        verbose_name = "Menu"
        verbose_name_plural = "Menus"
        ordering = ['priority', ]

    @staticmethod
    def get_root():
        return Menu.objects.filter(title="root").get()

    def not_deleted_children(self):
        return self.children.filter(deleted_at=None)

    def __str__(self):
        if self.parent:
            if self.parent.title != "root":
                return self.parent.title + ' : ' + self.title
        return self.title


FILE_CHOICES = (
    (1, 'Photo'),
    (2, 'Video')
)


class Slider(Timestampable):
    file = models.FileField(null=True, blank=True)
    label = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=True)
    fileType = models.PositiveIntegerField(default=1, choices=FILE_CHOICES)

    def __str__(self):
        return str(self.pk)


class Trailer(Timestampable):
    file = models.FileField(null=True, blank=True)

    def __str__(self):
        return str(self.pk)


class Coupon(Timestampable):
    title = models.CharField(max_length=255)
    package = models.ForeignKey(Package, on_delete=models.CASCADE)
    code = models.CharField(max_length=255)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount_percent = models.FloatField(default=0)

    def __str__(self):
        return self.title

website/templates/daysCreate.html
{% extends 'layouts/admin/base.html' %}

{% block head_title %}
    {{block.super}} | Days Create
{% endblock %}

{% block content %}
<section>
<div class="section-body contain-lg">
<h2>Days Create</h2>

    <div class="card">
        <div class="card-body">
            <form action="" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                 {% csrf_token %}
                {{form.as_p}}
                <button class="btn ink-reaction btn-primary btn-raised" type="submit">Add/Update</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#days').addClass('active')
</script>
{% endblock %}

website/templates/galleryUpdate.html
{% extends 'layouts/admin/base.html' %}

{% block head_title %}
    {{block.super}} | Gallery Update
{% endblock %}

{% block content %}
<section>
<div class="section-body contain-lg">
<h2>Gallery Update</h2>
    <div class="card">
        <div class="card-body">
            <form action="" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                 {% csrf_token %}
                {{form.as_p}}
                {{form.media}}
                <button class="btn ink-reaction btn-primary btn-raised" type="submit">Add/Update</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#gallery').addClass('active')
</script>
{% endblock %}

website/templates/pageCreate.html
{% extends 'layouts/admin/base.html' %}

{% block head_title %}
    {{block.super}} | Page Create
{% endblock %}

{% block content %}
<section>
<div class="section-body contain-lg">
<h2>Page Create</h2>
    <div class="card">
        <div class="card-body">
            <form action="" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                 {% csrf_token %}
                {{form.as_p}}
                {{form.media}}
                <button class="btn ink-reaction btn-primary btn-raised" type="submit">Add/Update</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#page').addClass('active')
</script>
{% endblock %}

website/templates/placeUpdate.html
{% extends 'layouts/admin/base.html' %}

{% block head_title %}
    {{block.super}} | Place Update
{% endblock %}

{% block content %}
<section>
<div class="section-body contain-lg">
<h2>Place Update</h2>
    <div class="card">
        <div class="card-body">
            <form action="" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
                 {% csrf_token %}
                {{form.as_p}}
                <button class="btn ink-reaction btn-primary btn-raised" type="submit">Add/Update</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#place').addClass('active')
</script>
{% endblock %}

website/templates/sliderList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}
{% load split %}


{% block head_title %}
    {{block.super}} | Slider List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-body">
<h2>Slider List</h2>
    <div class="card">
        <div class="card-body">
        <a  style="margin-bottom: 10px;z-index:1000;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'website:sliderCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover"  style="margin-bottom:30px">
                            <thead>
                                <tr>
                                    <th class="sort-numeric">Id</th>
                                    <th class="sort-alpha">File</th>
                                    <th class="sort-alpha">File Type</th>
                                    <th class="sort-alpha">Label</th>
                                    <th>Actions</th>
                            </thead>
                            <tbody>
                                {% for photo in photos %}
                                    <tr>
                                        <td class="sort-numeric"><a href="{% url 'website:sliderDetail' photo.id%}">{{photo.id}}</td>
                                        <td><a href="{% url 'website:sliderDetail' photo.id %}">{{photo.file.url|split:"/"}}</a></td>
                                        <td>{{photo.get_fileType_display}}</td>
                                        <td>{{photo.label}}</td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm">Action</button>
                                                <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                    <li><a href="{% url 'website:sliderUpdate' photo.pk %}"><i class="fa fa-edit"></i> Edit</a></li>
                                                    <li><a href="{% url 'website:sliderDelete' photo.pk %}"><i class="fa fa-trash"></i> Delete</a></li>
                                                </ul>
                                            </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#slider').addClass('active')
</script>>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}

website/templates/trailerList.html
{% extends 'layouts/admin/base.html' %}
{% load staticfiles %}
{% load split %}

{% block head_title %}
    {{block.super}} | Trailer List
{% endblock %}

{%block extra_head %}
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/jquery.dataTables.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.colVis.css' %}" />
<link type="text/css" rel="stylesheet" href="{% static 'assets/css/theme-default/libs/DataTables/extensions/dataTables.tableTools.css' %}" />
{% endblock %}

{% block content %}
<section>
<div class="section-body">
<h2>Trailer List</h2>
    <div class="card">
        <div class="card-body">
        <a  style="margin-bottom: 10px;" class="btn ink-reaction btn-floating-action btn-primary pull-right" href ="{% url 'website:trailerCreate' %}"><i class="fa fa-plus"></i></a>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table id="datatable1" class="table table-striped table-hover" style="margin-bottom:20px">
                            <thead>
                                <tr>
                                    <th class="sort-numeric">Id</th>
                                    <th class="sort-alpha">Link</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for trailer in trailers %}
                                    <tr>
                                        <td>{{trailer.id}}</td>
                                        <td><a href="{% url 'website:trailerDetail' trailer.id %}">{{trailer.file.url|split:"/"}}</a></td>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-sm">Action</button>
                                                <button type="button" class="btn dropdown-toggle btn-sm" data-toggle="dropdown"><i class="fa fa-caret-down"></i></button>
                                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                                    <li><a href="{% url 'website:trailerUpdate' trailer.id %}"><i class="fa fa-edit"></i> Edit</a></li>
                                                    <li><a href="{% url 'website:trailerDelete' trailer.id %}"><i class="fa fa-trash"></i> Delete</a></li>
                                                </ul>
                                            </div></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div><!--end .table-responsive -->
                </div><!--end .col -->
            </div><!--end .row -->
        </div>
    </div>
</div>
<br/>
</section>
{% endblock %}

{% block extra_js%}
<script type="text/javascript">
    $('#trailer').addClass('active')
</script>>
<script src="{% static 'assets/js/libs/DataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/ColVis/js/dataTables.colVis.min.js' %}"></script>
<script src="{% static 'assets/js/libs/DataTables/extensions/TableTools/js/dataTables.tableTools.min.js' %}"></script>
<script type='text/javascript'>
(function(namespace, $) {
    "use strict";
    var DemoTableDynamic = function() {
        var o = this;
        $(document).ready(function() {
            o.initialize();
        });

    };
    var p = DemoTableDynamic.prototype;
    p.initialize = function() {
        this._initDataTables();
    };
    p._initDataTables = function() {
        if (!$.isFunction($.fn.dataTable)) {
            return;
        }
        this._createDataTable1();
    };

    p._createDataTable1 = function() {
        $('#datatable1').DataTable({
            "dom": 'lCfrtip',
            "order": [],
            "colVis": {
                "buttonText": "Columns",
                "overlayFade": 0,
                "align": "right"
            },
            "language": {
                "lengthMenu": '_MENU_ entries per page',
                "search": '<i class="fa fa-search"></i>',
                "paginate": {
                    "previous": '<i class="fa fa-angle-left"></i>',
                    "next": '<i class="fa fa-angle-right"></i>'
                }
            }
        });
    };
    namespace.DemoTableDynamic = new DemoTableDynamic;
}(this.materialadmin, jQuery)); // pass in (namespace, jQuery):
</script>
{% endblock %}